-- RmtoSync | TTO accepted but image not yet uploaded (ITS chapter 1-4, up to 24h)
SELECT TOP (@BatchSize)
    p.PhotoId,
    p.LineId,
    cl.LineCode,
    p.FullPath,
    p.FileName,
    p.CapturedAt,
    p.ImportedAt,
    p.PlateP1,
    p.PlateP2,
    p.PlateP3,
    p.PlateP4,
    p.PlateConfidence,
    p.PlateBoxLeft,
    p.PlateBoxTop,
    p.PlateBoxWidth,
    p.PlateBoxHeight,
    p.PlateReadStatus,
    ISNULL(p.TerminalTtoRegistered, 0) AS TerminalTtoRegistered,
    p.TerminalPassInfoId,
    p.TerminalPackId,
    p.VehicleSpeed,
    p.AverageSpeed,
    p.TotalWeight,
    p.TotalAxles,
    p.AxleWeight1,
    p.AxleWeight2,
    p.AxleWeight3,
    p.AxleWeight4,
    p.AxleWeight5,
    p.AxleWeight6,
    p.AxleWeight7,
    p.AxleWeight8,
    p.AxleWeight9,
    p.CarClass13,
    p.Allowed,
    p.WrongDirection,
    p.SpeedType,
    p.VehicleClass,
    p.CrimeCodes,
    p.OcrScore,
    p.Longitude,
    p.Latitude,
    p.VehicleLen,
    p.HeadGap,
    p.Gap,
    p.FirstToLastAxlesLen,
    p.LengthAxles12,
    p.LengthAxles23,
    p.LengthAxles34,
    p.LengthAxles45,
    p.LengthAxles56,
    p.LengthAxles67,
    p.LengthAxles78,
    p.LengthAxlesMoreThan8,
    p.TotalWeightA,
    p.TotalWeightB,
    p.TotalWeightC,
    p.TotalOverWeight,
    p.PassInfoId,
    p.PreviousDeviceCode,
    p.TerminalTtoRegisteredAt,
    p.TerminalImageDeadlineAt,
    ISNULL(p.TerminalImageExpired, 0) AS TerminalImageExpired
FROM dbo.vw_CameraFullData p
INNER JOIN dbo.Lines cl ON cl.Id = p.LineId
WHERE p.TerminalSent = 0
  AND ISNULL(p.TerminalTtoRegistered, 0) = 1
  AND ISNULL(p.TerminalImageExpired, 0) = 0
  AND p.PlateReadStatus = 1
  AND p.TerminalImageDeadlineAt IS NOT NULL
  AND p.TerminalImageDeadlineAt > SYSDATETIME()
ORDER BY p.PhotoId ASC;
