// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleWeightMeasurementSystemDemo.Infrastructure.Persistence;

#nullable disable

namespace VehicleWeightMeasurementSystemDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923114724_AddMaxAllowedLimitsToVehicles")]
    partial class AddMaxAllowedLimitsToVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.AxleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AxleIndex")
                        .HasColumnType("int");

                    b.Property<double?>("Distance")
                        .HasColumnType("float");

                    b.Property<bool?>("IsOverweight")
                        .HasColumnType("bit");

                    b.Property<double?>("LengthToNext")
                        .HasColumnType("float");

                    b.Property<double?>("TimeMs")
                        .HasColumnType("float");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Axles", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AxleIndex = 1,
                            Distance = 0.0,
                            IsOverweight = false,
                            TimeMs = 100.0,
                            VehicleId = 1,
                            Weight = 8000.0
                        },
                        new
                        {
                            Id = 2,
                            AxleIndex = 2,
                            Distance = 4.2000000000000002,
                            IsOverweight = false,
                            TimeMs = 250.0,
                            VehicleId = 1,
                            Weight = 8200.0
                        },
                        new
                        {
                            Id = 3,
                            AxleIndex = 3,
                            Distance = 8.0999999999999996,
                            IsOverweight = false,
                            TimeMs = 400.0,
                            VehicleId = 1,
                            Weight = 8300.0
                        },
                        new
                        {
                            Id = 4,
                            AxleIndex = 1,
                            Distance = 0.0,
                            IsOverweight = false,
                            TimeMs = 120.0,
                            VehicleId = 2,
                            Weight = 9000.0
                        },
                        new
                        {
                            Id = 5,
                            AxleIndex = 2,
                            Distance = 5.5999999999999996,
                            IsOverweight = true,
                            TimeMs = 300.0,
                            VehicleId = 2,
                            Weight = 9000.0
                        },
                        new
                        {
                            Id = 6,
                            AxleIndex = 1,
                            Distance = 0.0,
                            IsOverweight = false,
                            TimeMs = 90.0,
                            VehicleId = 3,
                            Weight = 8000.0
                        },
                        new
                        {
                            Id = 7,
                            AxleIndex = 2,
                            Distance = 4.0,
                            IsOverweight = false,
                            TimeMs = 220.0,
                            VehicleId = 3,
                            Weight = 8000.0
                        },
                        new
                        {
                            Id = 8,
                            AxleIndex = 3,
                            Distance = 8.0,
                            IsOverweight = false,
                            TimeMs = 350.0,
                            VehicleId = 3,
                            Weight = 8000.0
                        },
                        new
                        {
                            Id = 9,
                            AxleIndex = 4,
                            Distance = 12.0,
                            IsOverweight = true,
                            TimeMs = 480.0,
                            VehicleId = 3,
                            Weight = 8000.0
                        });
                });

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.CameraPhotosEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileHash")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FullPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("LengthAxles12")
                        .HasColumnType("int");

                    b.Property<int?>("LengthAxles23")
                        .HasColumnType("int");

                    b.Property<int?>("LengthAxles34")
                        .HasColumnType("int");

                    b.Property<int?>("LengthAxles45")
                        .HasColumnType("int");

                    b.Property<int?>("LengthAxles56")
                        .HasColumnType("int");

                    b.Property<int?>("LengthAxles67")
                        .HasColumnType("int");

                    b.Property<int?>("LengthAxles78")
                        .HasColumnType("int");

                    b.Property<int?>("LengthAxlesMoreThan8")
                        .HasColumnType("int");

                    b.Property<long?>("PassInfoId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PlateBoxHeight")
                        .HasColumnType("int");

                    b.Property<int?>("PlateBoxLeft")
                        .HasColumnType("int");

                    b.Property<int?>("PlateBoxTop")
                        .HasColumnType("int");

                    b.Property<int?>("PlateBoxWidth")
                        .HasColumnType("int");

                    b.Property<string>("PlateFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateFullPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateP1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlateP2")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlateP3")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlateP4")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlateRelativePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("TerminalImageDeadlineAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TerminalImageExpired")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TerminalImageExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TerminalLastError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("TerminalPackId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TerminalPassInfoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TerminalSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TerminalSentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TerminalTtoRegistered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TerminalTtoRegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalWeightA")
                        .HasColumnType("int");

                    b.Property<int?>("TotalWeightB")
                        .HasColumnType("int");

                    b.Property<int?>("TotalWeightC")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TerminalImageDeadlineAt", "Id")
                        .HasDatabaseName("IX_CameraPhotos_TerminalImagePending")
                        .HasFilter("[TerminalSent] = 0 AND [TerminalTtoRegistered] = 1");

                    b.HasIndex("TerminalSent", "TerminalTtoRegistered", "TerminalImageExpired");

                    b.ToTable("CameraPhotos", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CapturedAt = new DateTime(2025, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            FileName = "car_00001.jpg",
                            FileSizeBytes = 204800L,
                            FullPath = "C:\\Temp\\Snapshots\\car_00001.jpg",
                            ImportedAt = new DateTime(2025, 1, 10, 8, 30, 2, 0, DateTimeKind.Unspecified),
                            PlateP1 = "۱۸",
                            PlateP2 = "س",
                            PlateP3 = "۲۴۴",
                            PlateP4 = "۱۱",
                            RelativePath = "Photos/car_00001.jpg",
                            TerminalImageExpired = false,
                            TerminalSent = true,
                            TerminalTtoRegistered = true,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2L,
                            CapturedAt = new DateTime(2025, 1, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            FileName = "car_00002.jpg",
                            FileSizeBytes = 185344L,
                            FullPath = "C:\\Temp\\Snapshots\\car_00002.jpg",
                            ImportedAt = new DateTime(2025, 1, 10, 9, 15, 2, 0, DateTimeKind.Unspecified),
                            PlateP1 = "۷۷",
                            PlateP2 = "ب",
                            PlateP3 = "۵۵۵",
                            PlateP4 = "۴۴",
                            RelativePath = "Photos/car_00002.jpg",
                            TerminalImageExpired = false,
                            TerminalSent = false,
                            TerminalTtoRegistered = false,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.LineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LineCode")
                        .IsUnique();

                    b.ToTable("Lines", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LineCode = "L1",
                            LineName = "Line1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LineCode = "L2",
                            LineName = "Line2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LineCode = "L3",
                            LineName = "Line3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LineCode = "L4",
                            LineName = "Line4"
                        });
                });

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.LogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exception")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogEvent")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MessageTemplate")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Properties")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logs", "dbo");
                });

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.VehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ADC1")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ADC2")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ADC3")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ADC4")
                        .HasColumnType("varchar(16)");

                    b.Property<bool?>("Allowed")
                        .HasColumnType("bit");

                    b.Property<double?>("AverageSpeed")
                        .HasColumnType("float");

                    b.Property<int?>("AxleCount")
                        .HasColumnType("int");

                    b.Property<string>("CrimeCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gap")
                        .HasColumnType("int");

                    b.Property<int?>("HeadGap")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<int?>("LineId")
                        .HasColumnType("int");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MaxAllowedSpeedForClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(110);

                    b.Property<double>("MaxAllowedWeightForClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(44000.0);

                    b.Property<double?>("PlateConfidence")
                        .HasColumnType("float");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PlateReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlateReadStatus")
                        .HasColumnType("int");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<int?>("SpeedType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<double>("TotalOverWeight")
                        .HasColumnType("float");

                    b.Property<double?>("TotalWeight")
                        .HasColumnType("float");

                    b.Property<int?>("VehicleClass")
                        .HasColumnType("int");

                    b.Property<double?>("VehicleLen")
                        .HasColumnType("float");

                    b.Property<string>("WimRawLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WrongDirection")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("Timestamp");

                    b.ToTable("Vehicles", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allowed = true,
                            AverageSpeed = 60.0,
                            AxleCount = 3,
                            LineId = 2,
                            MaxAllowedSpeedForClass = 110,
                            MaxAllowedWeightForClass = 44000.0,
                            PlateConfidence = 92.5,
                            PlateNumber = "‏۱۱ ایران ۲۴۴ س ۱۸",
                            PlateReadAt = new DateTime(2025, 1, 10, 8, 30, 1, 0, DateTimeKind.Unspecified),
                            PlateReadStatus = 1,
                            Speed = 62.5,
                            Timestamp = new DateTime(2025, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            TotalOverWeight = 0.0,
                            TotalWeight = 24500.0,
                            VehicleClass = 2,
                            VehicleLen = 12.4,
                            WrongDirection = false
                        },
                        new
                        {
                            Id = 2,
                            Allowed = true,
                            AverageSpeed = 52.0,
                            AxleCount = 2,
                            LineId = 1,
                            MaxAllowedSpeedForClass = 110,
                            MaxAllowedWeightForClass = 44000.0,
                            PlateConfidence = 88.0,
                            PlateNumber = "‏۴۴ ایران ۵۵۵ ب ۷۷",
                            PlateReadAt = new DateTime(2025, 1, 10, 9, 15, 1, 0, DateTimeKind.Unspecified),
                            PlateReadStatus = 1,
                            Speed = 55.0,
                            Timestamp = new DateTime(2025, 1, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            TotalOverWeight = 500.0,
                            TotalWeight = 18000.0,
                            VehicleClass = 3,
                            VehicleLen = 9.8000000000000007,
                            WrongDirection = false
                        },
                        new
                        {
                            Id = 3,
                            Allowed = false,
                            AverageSpeed = 45.0,
                            AxleCount = 4,
                            LineId = 4,
                            MaxAllowedSpeedForClass = 110,
                            MaxAllowedWeightForClass = 44000.0,
                            PlateConfidence = 75.5,
                            PlateNumber = "‏۳۳ ایران ۱۱۲ ب ۹۹",
                            PlateReadAt = new DateTime(2025, 1, 10, 10, 5, 1, 0, DateTimeKind.Unspecified),
                            PlateReadStatus = 1,
                            Speed = 48.0,
                            Timestamp = new DateTime(2025, 1, 10, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            TotalOverWeight = 3500.0,
                            TotalWeight = 32000.0,
                            VehicleClass = 4,
                            VehicleLen = 15.199999999999999,
                            WrongDirection = false
                        });
                });

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.AxleEntity", b =>
                {
                    b.HasOne("VehicleWeightMeasurementSystemDemo.Domain.Entities.VehicleEntity", "Vehicle")
                        .WithMany("Axles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.CameraPhotosEntity", b =>
                {
                    b.HasOne("VehicleWeightMeasurementSystemDemo.Domain.Entities.VehicleEntity", "Vehicle")
                        .WithMany("Photos")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.VehicleEntity", b =>
                {
                    b.HasOne("VehicleWeightMeasurementSystemDemo.Domain.Entities.LineEntity", "Line")
                        .WithMany("Vehicles")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Line");
                });

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.LineEntity", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleWeightMeasurementSystemDemo.Domain.Entities.VehicleEntity", b =>
                {
                    b.Navigation("Axles");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
